project_id = "qherclscaqbxytlgbunl"

[functions.register-supporter]
verify_jwt = false

[functions.calculate-ied]
verify_jwt = false

[functions.register-contratado]
verify_jwt = false

[functions.register-funcionario]
verify_jwt = false

[functions.manage-whatsapp-instance]
verify_jwt = false

[functions.send-whatsapp-dispatch]
verify_jwt = false

[functions.send-birthday-messages]
verify_jwt = false

[functions.analyze-crisis]
verify_jwt = false

[functions.check-presence-absences]
verify_jwt = false

[functions.whatsapp-inbound-webhook]
verify_jwt = false